### PR TITLE
New site

### PR DESCRIPTION
**Pull request by anthonycr0**

### CODE REVIEW

**Comment by hugomd** [comment]
Nice to see you using Now! ✨

**Comment by anthonycr0** [comment]
ugh https://github.com/terser-js/terser/pull/254

**Comment by terencehuynh** [comment]
@anthonycr0 We could also use Netlify? The benefit of that is that we get previews on branches.

Unless you're planning to do something special rather than a SPA?

**Comment by hugomd** [comment]
@terencehuynh Now offers deployment previews, and it's enabled for this PR!
image

**Pull request merged**
